#!/usr/bin/env python3
"""Generate pinned Unicode data modules and test vectors from Python's UCD.

Python owns only offline data derivation. Hand-maintained Luau modules own every
runtime algorithm; Framework execution never imports Python or host Unicode
tables. Regeneration deliberately refuses a different UCD version so an SDK
Unicode upgrade must be an explicit identity-moving change.

Three files are generated. Two are the runtime data modules the SDK loads. The
third is the normalization conformance corpus under ``tests/task/``, derived
from the same pinned UCD by the same refusal, so the suite that drives it needs
no network at test time.

The derived category data is distributed with the Unicode License v3 notice in
``modules/task/runtime/UNICODE-LICENSE.txt``.
"""

from __future__ import annotations

import argparse
import hashlib
import unicodedata
from pathlib import Path


PINNED_UNICODE_VERSION = "15.0.0"
UTF8_DATA_OUTPUT = Path("modules/task/runtime/unicode-utf8-data.luau")
UTF8_DATA_OUTPUT_SHA256 = "c68e79be9cfa2c6ef9679c41ff30fedee7e4230dcafe1d918496d9b1b4796033"
TEXT_DATA_OUTPUT = Path("modules/task/runtime/unicode-text-data.luau")
TEXT_DATA_OUTPUT_SHA256 = "e7a2fbc53ec58081b78fa0c4ce56ac20f10a745d9ba3124f10d38e117282cfa4"

# The normalization conformance corpus. It is a TEST input rather than a runtime
# one, so it is deliberately not under modules/task/runtime/: everything there is
# embedded into the shipped Framework bundle by scripts/embed_luau.py.
CONFORMANCE_OUTPUT = Path("tests/task/unicode-normalization-vectors.generated.hpp")
CONFORMANCE_OUTPUT_SHA256 = "9cc65d337241faffb2ce415c19b48a621674fba4025416d94fa24dd24d33fc48"

# One C++ string literal holds at most this many bytes of the corpus. MSVC caps
# a single literal at 16383 bytes (C2026) and adjacent-literal concatenation does
# not count toward it, so the chunk size only trades literal count against
# literal length.
CONFORMANCE_CHUNK_BYTES = 2000

# Deterministic samples for the parts of the corpus that are combinations rather
# than single characters. Every one of these is a stride or a count over data
# sorted by code point, so the corpus is a function of the pinned UCD alone.
CANONICAL_ORDER_STARTER_COUNT = 24
CANONICAL_ORDER_MARK_COUNT = 12
TRIVIAL_SAMPLE_STRIDE = 1021
HANGUL_LEADING_SAMPLE = (0, 9, 18)
HANGUL_VOWEL_SAMPLE = (0, 10, 20)
HANGUL_TRAILING_SAMPLE = (0, 1, 27)

MAJOR_CATEGORY_NAMES = {
    "C": "other",
    "L": "letter",
    "M": "mark",
    "N": "number",
    "P": "punctuation",
    "S": "symbol",
    "Z": "separator",
}

# Unicode White_Space from PropList for Unicode 15.0.0. These authored ranges
# make the property explicit; Python's str.isspace also includes four legacy C0
# information separators and therefore is not the property this API promises.
WHITE_SPACE_RANGES = (
    (0x0009, 0x000D),
    (0x0020, 0x0020),
    (0x0085, 0x0085),
    (0x00A0, 0x00A0),
    (0x1680, 0x1680),
    (0x2000, 0x200A),
    (0x2028, 0x2029),
    (0x202F, 0x202F),
    (0x205F, 0x205F),
    (0x3000, 0x3000),
)


def major_category_ranges() -> list[tuple[int, int, str]]:
    ranges: list[tuple[int, int, str]] = []
    start = 0
    previous = unicodedata.category(chr(0))[0]
    for codepoint in range(1, 0x110000):
        current = unicodedata.category(chr(codepoint))[0]
        if current == previous:
            continue
        ranges.append((start, codepoint - 1, MAJOR_CATEGORY_NAMES[previous]))
        start = codepoint
        previous = current
    ranges.append((start, 0x10FFFF, MAJOR_CATEGORY_NAMES[previous]))
    return ranges


def lua_ranges(rows: list[tuple[int, int, str]]) -> str:
    return "\n".join(
        f'    {{{start}, {end}, "{name}"}},' for start, end, name in rows
    )


def lua_numeric_ranges(rows: tuple[tuple[int, int], ...]) -> str:
    return "\n".join(f"    {{{start}, {end}}}," for start, end in rows)


def render_utf8_data() -> str:
    if unicodedata.unidata_version != PINNED_UNICODE_VERSION:
        raise SystemExit(
            "generate_unicode_luau.py requires Python UCD "
            f"{PINNED_UNICODE_VERSION}, got {unicodedata.unidata_version}"
        )

    return f'''-- GENERATED by scripts/generate_unicode_luau.py; do not edit.
-- Derived Unicode 15.0 category and White_Space data only.
-- Runtime algorithms live in the hand-maintained utf8.luau module.
--!strict

local data = {{
    unicode_version = "{PINNED_UNICODE_VERSION}",
    category_ranges = {{
{lua_ranges(major_category_ranges())}
    }},
    white_space_ranges = {{
{lua_numeric_ranges(WHITE_SPACE_RANGES)}
    }},
}}

return table.freeze(data)
'''


def decomposition_maps() -> tuple[
    list[tuple[int, list[int]]], list[tuple[int, list[int]]]
]:
    canonical: list[tuple[int, list[int]]] = []
    compatibility: list[tuple[int, list[int]]] = []
    for codepoint in range(0x110000):
        decomposition = unicodedata.decomposition(chr(codepoint))
        if not decomposition:
            continue
        fields = decomposition.split()
        tagged = fields[0].startswith("<")
        mapping_start = 1 if tagged else 0
        values = [int(field, 16) for field in fields[mapping_start:]]
        (compatibility if tagged else canonical).append((codepoint, values))
    return canonical, compatibility


def combining_classes() -> list[tuple[int, int]]:
    return [
        (codepoint, value)
        for codepoint in range(0x110000)
        if (value := unicodedata.combining(chr(codepoint))) != 0
    ]


def case_fold_maps() -> list[tuple[int, list[int]]]:
    rows: list[tuple[int, list[int]]] = []
    for codepoint in range(0x110000):
        source = chr(codepoint)
        folded = source.casefold()
        if folded != source:
            rows.append((codepoint, [ord(value) for value in folded]))
    return rows


def composition_maps() -> list[tuple[int, int, int]]:
    rows: list[tuple[int, int, int]] = []
    for codepoint in range(0x110000):
        decomposition = unicodedata.decomposition(chr(codepoint))
        if not decomposition or decomposition.startswith("<"):
            continue
        values = [int(field, 16) for field in decomposition.split()]
        if len(values) != 2 or unicodedata.combining(chr(values[0])) != 0:
            continue
        source = "".join(chr(value) for value in values)
        if unicodedata.normalize("NFC", source) == chr(codepoint):
            rows.append((values[0], values[1], codepoint))
    return rows


def packed_mappings(rows: list[tuple[int, list[int]]]) -> str:
    return "\n".join(
        f"{codepoint}:" + ",".join(str(value) for value in values)
        for codepoint, values in rows
    )


def packed_pairs(rows: list[tuple[int, int]]) -> str:
    return "\n".join(f"{left}:{right}" for left, right in rows)


def packed_compositions(rows: list[tuple[int, int, int]]) -> str:
    return "\n".join(
        f"{starter},{combining}:{composite}"
        for starter, combining, composite in rows
    )


def render_text_data() -> str:
    if unicodedata.unidata_version != PINNED_UNICODE_VERSION:
        raise SystemExit(
            "generate_unicode_luau.py requires Python UCD "
            f"{PINNED_UNICODE_VERSION}, got {unicodedata.unidata_version}"
        )

    canonical, compatibility = decomposition_maps()
    template = r'''-- GENERATED by scripts/generate_unicode_luau.py; do not edit.
-- Derived Unicode 15.0 normalization and full case-folding data only.
-- Runtime algorithms live in the hand-maintained text.luau module.
--!strict

local data = {
    unicode_version = "@@VERSION@@",
    canonical = [=[@@CANONICAL@@]=],
    compatibility = [=[@@COMPATIBILITY@@]=],
    combining_classes = [=[@@COMBINING@@]=],
    compositions = [=[@@COMPOSITION@@]=],
    case_folds = [=[@@CASEFOLD@@]=],
}

return table.freeze(data)
'''
    return (
        template.replace("@@VERSION@@", PINNED_UNICODE_VERSION)
        .replace("@@CANONICAL@@", packed_mappings(canonical))
        .replace("@@COMPATIBILITY@@", packed_mappings(compatibility))
        .replace("@@COMBINING@@", packed_pairs(combining_classes()))
        .replace("@@COMPOSITION@@", packed_compositions(composition_maps()))
        .replace("@@CASEFOLD@@", packed_mappings(case_fold_maps()))
    )


def normalization_forms(source: str) -> tuple[str, str, str, str]:
    return (
        unicodedata.normalize("NFC", source),
        unicodedata.normalize("NFD", source),
        unicodedata.normalize("NFKC", source),
        unicodedata.normalize("NFKD", source),
    )


def conformance_row(source: str) -> str:
    """One NormalizationTest.txt-shaped line: c1;c2;c3;c4;c5."""
    fields = (source, *normalization_forms(source))
    return ";".join(
        " ".join(f"{ord(character):04X}" for character in field) for field in fields
    )


def is_scalar(codepoint: int) -> bool:
    return not 0xD800 <= codepoint <= 0xDFFF


def per_character_sources() -> list[str]:
    """Every character whose normalization is not itself, in code point order.

    This is the corpus NormalizationTest.txt calls Part 1, derived rather than
    copied: a character belongs here exactly when one of its four forms differs
    from it.
    """
    return [
        chr(codepoint)
        for codepoint in range(0x110000)
        if is_scalar(codepoint)
        and any(form != chr(codepoint) for form in normalization_forms(chr(codepoint)))
    ]


def canonical_order_sources() -> list[str]:
    """Starter-plus-two-marks combinations, the Part 2 shape.

    Both the starters and the marks are read out of the pinned UCD rather than
    listed here: the starters are the first N code points that begin a canonical
    composition, and the marks are an even stride through the combining
    characters, which is what spreads them across combining classes. Emitting
    each unordered mark pair in BOTH orders is the point of the corpus -- the two
    orderings must produce the same canonical order.
    """
    starters = sorted({starter for starter, _combining, _composite in composition_maps()})
    starters = starters[:CANONICAL_ORDER_STARTER_COUNT]

    combining = [codepoint for codepoint, _value in combining_classes()]
    if not combining:
        return []
    stride = max(1, len(combining) // CANONICAL_ORDER_MARK_COUNT)
    marks = combining[::stride][:CANONICAL_ORDER_MARK_COUNT]

    sources: list[str] = []
    for starter in starters:
        for first in marks:
            for second in marks:
                if unicodedata.combining(chr(first)) == unicodedata.combining(
                    chr(second)
                ):
                    continue
                sources.append(chr(starter) + chr(first) + chr(second))
    return sources


def trivial_sample_sources(covered: set[int]) -> list[str]:
    """A stride sample of characters whose four forms are all themselves.

    NormalizationTest.txt states this as invariant c5 over every character it
    does not list. Running it over all 1.1 million would dominate the suite for
    the least information, so a prime stride samples it instead; the stride is
    fixed, so the sample is the same on every machine.
    """
    return [
        chr(codepoint)
        for codepoint in range(0, 0x110000, TRIVIAL_SAMPLE_STRIDE)
        if is_scalar(codepoint) and codepoint not in covered
    ]


def hangul_sources() -> list[str]:
    """Jamo sequences and the syllables they compose to.

    Hangul composition and decomposition are arithmetic rather than table
    lookups in UAX #15, so they are the one part of the algorithm the
    per-character corpus above exercises only from the syllable side.
    """
    leading_base = 0x1100
    vowel_base = 0x1161
    trailing_base = 0x11A7
    syllable_base = 0xAC00
    trailing_count = 28
    vowel_count = 21

    sources: list[str] = []
    for leading in HANGUL_LEADING_SAMPLE:
        for vowel in HANGUL_VOWEL_SAMPLE:
            for trailing in HANGUL_TRAILING_SAMPLE:
                jamo = chr(leading_base + leading) + chr(vowel_base + vowel)
                syllable = syllable_base + (
                    leading * vowel_count + vowel
                ) * trailing_count
                if trailing != 0:
                    jamo += chr(trailing_base + trailing)
                    syllable += trailing
                sources.append(jamo)
                sources.append(chr(syllable))
    return sources


def conformance_corpus() -> list[str]:
    per_character = per_character_sources()
    covered = {ord(source) for source in per_character if len(source) == 1}
    return [
        *(conformance_row(source) for source in per_character),
        *(conformance_row(source) for source in canonical_order_sources()),
        *(conformance_row(source) for source in trivial_sample_sources(covered)),
        *(conformance_row(source) for source in hangul_sources()),
    ]


def conformance_literals(corpus: str) -> str:
    data = corpus.encode("ascii")
    pieces: list[str] = []
    offset = 0
    while offset < len(data):
        piece = data[offset : offset + CONFORMANCE_CHUNK_BYTES]
        # Never split a line across two literals: the concatenation is the same
        # either way, but a reader diffing this file wants whole rows.
        boundary = piece.rfind(b"\n")
        if boundary != -1 and offset + len(piece) < len(data):
            piece = piece[: boundary + 1]
        pieces.append(piece.decode("ascii").replace("\n", "\\n"))
        offset += len(piece)
    return "\n".join(f'    "{piece}"' for piece in pieces)


def render_conformance() -> str:
    if unicodedata.unidata_version != PINNED_UNICODE_VERSION:
        raise SystemExit(
            "generate_unicode_luau.py requires Python UCD "
            f"{PINNED_UNICODE_VERSION}, got {unicodedata.unidata_version}"
        )

    rows = conformance_corpus()
    corpus = "".join(f"{row}\n" for row in rows)
    return f'''// GENERATED by scripts/generate_unicode_luau.py; do not edit.
//
// Unicode {PINNED_UNICODE_VERSION} normalization conformance vectors, in the exact five-field
// layout of the UCD\'s own NormalizationTest.txt: one row per line, written
// `c1;c2;c3;c4;c5`, where the fields are the source and its NFC, NFD, NFKC and
// NFKD forms, and each field is one or more space-separated uppercase hex code
// points. tests/task/test-unicode-normalization-conformance.cpp asserts the five
// invariants that file states over these rows.
//
// PROVENANCE, and what this is not. These are NOT the UCD\'s own
// NormalizationTest.txt. That file is not vendored in this repository and is not
// shipped with CPython, so it is not available offline, and a suite that
// downloaded it at test time would not be reproducible. What IS available
// offline is the input every other pinned Unicode table here is already derived
// from: CPython\'s `unicodedata`, refused by this generator unless its UCD is
// exactly {PINNED_UNICODE_VERSION}. Its normalizer is an independent C implementation of
// UAX #15 that shares no code with the hand-maintained Luau algorithm these rows
// drive, so it is an oracle and not a second copy of the subject.
//
// The corpus is derived, never authored. It is, in order: every character whose
// normalization is not itself (the Part 1 shape); starter-plus-two-marks
// combinations built from the pinned composition and combining-class tables,
// each mark pair in both orders (the Part 2 shape); a fixed prime stride through
// the characters whose four forms are all themselves (invariant c5); and Hangul
// jamo sequences with the syllables they compose to.

#pragma once

#include <cstddef>
#include <string_view>

namespace uf::task::testing
{{
    // The UCD release these rows were derived from. The suite compares it with
    // `text.unicode_version`, so vectors from one Unicode version can never be
    // run against a table pinned to another.
    constexpr auto k_unicodeNormalizationVectorVersion =
        std::string_view{{"{PINNED_UNICODE_VERSION}"}};

    // How many rows the corpus holds. Published so the suite can refuse a corpus
    // that silently shrank rather than reporting a pass over what is left.
    constexpr auto k_unicodeNormalizationVectorCount = std::size_t{{{len(rows)}U}};

    constexpr auto k_unicodeNormalizationVectors = std::string_view{{
{conformance_literals(corpus)}
    }};
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="repository root",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when a committed Unicode data module differs",
    )
    arguments = parser.parse_args()
    root = arguments.root.resolve()
    outputs = (
        (UTF8_DATA_OUTPUT, UTF8_DATA_OUTPUT_SHA256, render_utf8_data),
        (TEXT_DATA_OUTPUT, TEXT_DATA_OUTPUT_SHA256, render_text_data),
        (CONFORMANCE_OUTPUT, CONFORMANCE_OUTPUT_SHA256, render_conformance),
    )
    if arguments.check:
        for relative, pinned_digest, renderer in outputs:
            output = root / relative
            if not output.is_file():
                print(f"{relative}: is missing", flush=True)
                return 1
            committed = output.read_bytes()
            digest = hashlib.sha256(committed).hexdigest()
            if not pinned_digest or digest != pinned_digest:
                print(
                    f"{relative}: SHA-256 {digest} differs from pinned "
                    f"{pinned_digest or '<unset>'}",
                    flush=True,
                )
                return 1
            if unicodedata.unidata_version == PINNED_UNICODE_VERSION:
                generated = renderer().encode("utf-8")
                if committed != generated:
                    print(
                        f"{relative}: differs from pinned Unicode generation",
                        flush=True,
                    )
                    return 1
        print(
            f"Unicode Luau check OK ({len(outputs)} generated files, UCD "
            f"{PINNED_UNICODE_VERSION})."
        )
        return 0
    for relative, _pinned_digest, renderer in outputs:
        generated = renderer()
        output = root / relative
        output.write_text(generated, encoding="utf-8", newline="\n")
        digest = hashlib.sha256(generated.encode("utf-8")).hexdigest()
        print(
            f"Unicode Luau generated ({len(generated)} bytes, SHA-256 "
            f"{digest}): {relative}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
