#!/usr/bin/env python3
"""Generate the pinned pure-Luau Unicode SDK modules from Python's UCD.

Python is an offline data-pipeline owner only. The committed Luau files contain
every runtime byte; Framework execution never imports Python or host Unicode
tables. Regeneration deliberately refuses a different UCD version so an SDK
Unicode upgrade must be an explicit identity-moving change.

The derived category data is distributed with the Unicode License v3 notice in
``modules/task/runtime/UNICODE-LICENSE.txt``.
"""

from __future__ import annotations

import argparse
import hashlib
import unicodedata
from pathlib import Path


PINNED_UNICODE_VERSION = "15.0.0"
UTF8_OUTPUT = Path("modules/task/runtime/utf8.luau")
UTF8_OUTPUT_SHA256 = "82d4e58e0c15e8e07ca5c4828f64c59ee7c8b15dbe30c33e17fdefbe5cd98c90"
TEXT_OUTPUT = Path("modules/task/runtime/text.luau")
TEXT_OUTPUT_SHA256 = "422543c5a35afbb1cfbfb6c565beef217d38f2c177c3414e10d9e10b79711be2"

MAJOR_CATEGORY_NAMES = {
    "C": "other",
    "L": "letter",
    "M": "mark",
    "N": "number",
    "P": "punctuation",
    "S": "symbol",
    "Z": "separator",
}

# Unicode White_Space from PropList for Unicode 15.0.0. These authored ranges
# make the property explicit; Python's str.isspace also includes four legacy C0
# information separators and therefore is not the property this API promises.
WHITE_SPACE_RANGES = (
    (0x0009, 0x000D),
    (0x0020, 0x0020),
    (0x0085, 0x0085),
    (0x00A0, 0x00A0),
    (0x1680, 0x1680),
    (0x2000, 0x200A),
    (0x2028, 0x2029),
    (0x202F, 0x202F),
    (0x205F, 0x205F),
    (0x3000, 0x3000),
)


def major_category_ranges() -> list[tuple[int, int, str]]:
    ranges: list[tuple[int, int, str]] = []
    start = 0
    previous = unicodedata.category(chr(0))[0]
    for codepoint in range(1, 0x110000):
        current = unicodedata.category(chr(codepoint))[0]
        if current == previous:
            continue
        ranges.append((start, codepoint - 1, MAJOR_CATEGORY_NAMES[previous]))
        start = codepoint
        previous = current
    ranges.append((start, 0x10FFFF, MAJOR_CATEGORY_NAMES[previous]))
    return ranges


def lua_ranges(rows: list[tuple[int, int, str]]) -> str:
    return "\n".join(
        f'    {{{start}, {end}, "{name}"}},' for start, end, name in rows
    )


def lua_numeric_ranges(rows: tuple[tuple[int, int], ...]) -> str:
    return "\n".join(f"    {{{start}, {end}}}," for start, end in rows)


def render_utf8() -> str:
    if unicodedata.unidata_version != PINNED_UNICODE_VERSION:
        raise SystemExit(
            "generate_unicode_luau.py requires Python UCD "
            f"{PINNED_UNICODE_VERSION}, got {unicodedata.unidata_version}"
        )

    return f'''-- GENERATED by scripts/generate_unicode_luau.py; do not edit.
-- Python owns this offline data derivation. Runtime behavior is entirely in
-- these committed, release-hashed bytes and never consults the host locale.
--!strict

local builtinUtf8 = utf8
local utf8 = {{}}

utf8.unicode_version = "{PINNED_UNICODE_VERSION}"

local categoryRanges = {{
{lua_ranges(major_category_ranges())}
}}

local whiteSpaceRanges = {{
{lua_numeric_ranges(WHITE_SPACE_RANGES)}
}}

local function reject(message: string): never
    error("utf8 " .. message, 3)
end

local function checkedText(value: any, where: string): (string, number)
    if type(value) ~= "string" then reject(where .. " must be a string") end
    local ok, length = pcall(builtinUtf8.len, value)
    if not ok or length == nil then reject(where .. " is not valid UTF-8") end
    return value, length
end

local function checkedCodepoint(value: any): number
    if type(value) == "string" then
        local text, length = checkedText(value, "classify input")
        if length ~= 1 then reject("classify string must hold one code point") end
        return builtinUtf8.codepoint(text)
    end
    if type(value) ~= "number" or value % 1 ~= 0 or value < 0
        or value > 0x10FFFF or (value >= 0xD800 and value <= 0xDFFF)
    then
        reject("code point is not a Unicode scalar value")
    end
    return value
end

local function rangeValue(ranges: any, codepoint: number): any?
    local low = 1
    local high = #ranges
    while low <= high do
        local middle = math.floor((low + high) / 2)
        local row = ranges[middle]
        if codepoint < row[1] then
            high = middle - 1
        elseif codepoint > row[2] then
            low = middle + 1
        else
            return row[3] or true
        end
    end
    return nil
end

function utf8.is_valid(value: any): boolean
    if type(value) ~= "string" then return false end
    local ok, length = pcall(builtinUtf8.len, value)
    return ok and length ~= nil
end

function utf8.validate(value: any): string
    local text = checkedText(value, "value")
    return text
end

function utf8.length(value: any): number
    local _, length = checkedText(value, "value")
    return length
end

function utf8.codepoints(value: any): any
    local text = checkedText(value, "value")
    local output: {{ number }} = {{}}
    for _, codepoint in builtinUtf8.codes(text) do
        table.insert(output, codepoint)
    end
    return table.freeze(output)
end

function utf8.slice(value: any, first: any, last: any?): string
    local text, length = checkedText(value, "value")
    if type(first) ~= "number" or first % 1 ~= 0 or first < 1
        or first > length + 1
    then
        reject("slice first index is outside the code-point sequence")
    end
    local final = if last == nil then length else last
    if type(final) ~= "number" or final % 1 ~= 0 or final < 0 or final > length then
        reject("slice last index is outside the code-point sequence")
    end
    if final < first then return "" end
    local firstByte = builtinUtf8.offset(text, first)
    local afterByte = if final == length
        then #text + 1
        else builtinUtf8.offset(text, final + 1)
    return string.sub(text, firstByte, afterByte - 1)
end

function utf8.classify(value: any): string
    local codepoint = checkedCodepoint(value)
    return rangeValue(categoryRanges, codepoint) or "other"
end

function utf8.is_whitespace(value: any): boolean
    return rangeValue(whiteSpaceRanges, checkedCodepoint(value)) == true
end

return table.freeze(utf8)
'''


def decomposition_maps() -> tuple[
    list[tuple[int, list[int]]], list[tuple[int, list[int]]]
]:
    canonical: list[tuple[int, list[int]]] = []
    compatibility: list[tuple[int, list[int]]] = []
    for codepoint in range(0x110000):
        decomposition = unicodedata.decomposition(chr(codepoint))
        if not decomposition:
            continue
        fields = decomposition.split()
        tagged = fields[0].startswith("<")
        mapping_start = 1 if tagged else 0
        values = [int(field, 16) for field in fields[mapping_start:]]
        (compatibility if tagged else canonical).append((codepoint, values))
    return canonical, compatibility


def combining_classes() -> list[tuple[int, int]]:
    return [
        (codepoint, value)
        for codepoint in range(0x110000)
        if (value := unicodedata.combining(chr(codepoint))) != 0
    ]


def case_fold_maps() -> list[tuple[int, list[int]]]:
    rows: list[tuple[int, list[int]]] = []
    for codepoint in range(0x110000):
        source = chr(codepoint)
        folded = source.casefold()
        if folded != source:
            rows.append((codepoint, [ord(value) for value in folded]))
    return rows


def composition_maps() -> list[tuple[int, int, int]]:
    rows: list[tuple[int, int, int]] = []
    for codepoint in range(0x110000):
        decomposition = unicodedata.decomposition(chr(codepoint))
        if not decomposition or decomposition.startswith("<"):
            continue
        values = [int(field, 16) for field in decomposition.split()]
        if len(values) != 2 or unicodedata.combining(chr(values[0])) != 0:
            continue
        source = "".join(chr(value) for value in values)
        if unicodedata.normalize("NFC", source) == chr(codepoint):
            rows.append((values[0], values[1], codepoint))
    return rows


def packed_mappings(rows: list[tuple[int, list[int]]]) -> str:
    return "\n".join(
        f"{codepoint}:" + ",".join(str(value) for value in values)
        for codepoint, values in rows
    )


def packed_pairs(rows: list[tuple[int, int]]) -> str:
    return "\n".join(f"{left}:{right}" for left, right in rows)


def packed_compositions(rows: list[tuple[int, int, int]]) -> str:
    return "\n".join(
        f"{starter},{combining}:{composite}"
        for starter, combining, composite in rows
    )


def render_text() -> str:
    if unicodedata.unidata_version != PINNED_UNICODE_VERSION:
        raise SystemExit(
            "generate_unicode_luau.py requires Python UCD "
            f"{PINNED_UNICODE_VERSION}, got {unicodedata.unidata_version}"
        )

    canonical, compatibility = decomposition_maps()
    template = r'''-- GENERATED by scripts/generate_unicode_luau.py; do not edit.
-- Unicode normalization and full case folding use only these committed,
-- release-hashed Unicode 15.0 data bytes. No host locale is consulted.
--!strict

local builtinUtf8 = utf8
local unicode = require("@umbraflow/utf8")
local text = {}

text.unicode_version = "@@VERSION@@"

local canonicalData = [=[@@CANONICAL@@]=]
local compatibilityData = [=[@@COMPATIBILITY@@]=]
local combiningClassData = [=[@@COMBINING@@]=]
local compositionData = [=[@@COMPOSITION@@]=]
local caseFoldData = [=[@@CASEFOLD@@]=]

local function reject(message: string): never
    error("text " .. message, 3)
end

local function parseMappings(data: string): any
    local output = {}
    for row in string.gmatch(data, "[^\n]+") do
        local separator = string.find(row, ":", 1, true)
        if separator == nil then reject("has corrupt generated mapping data") end
        local codepoint = tonumber(string.sub(row, 1, separator - 1))
        local values = {}
        for value in string.gmatch(string.sub(row, separator + 1), "%d+") do
            table.insert(values, tonumber(value))
        end
        output[codepoint] = values
    end
    return output
end

local function parsePairs(data: string): any
    local output = {}
    for row in string.gmatch(data, "[^\n]+") do
        local separator = string.find(row, ":", 1, true)
        if separator == nil then reject("has corrupt generated pair data") end
        output[tonumber(string.sub(row, 1, separator - 1))] =
            tonumber(string.sub(row, separator + 1))
    end
    return output
end

local function parseCompositions(data: string): any
    local output = {}
    for row in string.gmatch(data, "[^\n]+") do
        local comma = string.find(row, ",", 1, true)
        local colon = string.find(row, ":", 1, true)
        if comma == nil or colon == nil then
            reject("has corrupt generated composition data")
        end
        local starter = tonumber(string.sub(row, 1, comma - 1))
        local combining = tonumber(string.sub(row, comma + 1, colon - 1))
        local byCombining = output[starter]
        if byCombining == nil then
            byCombining = {}
            output[starter] = byCombining
        end
        byCombining[combining] = tonumber(string.sub(row, colon + 1))
    end
    return output
end

local canonical = parseMappings(canonicalData)
local compatibility = parseMappings(compatibilityData)
local combiningClasses = parsePairs(combiningClassData)
local compositions = parseCompositions(compositionData)
local caseFolds = parseMappings(caseFoldData)

local SBase = 0xAC00
local LBase = 0x1100
local VBase = 0x1161
local TBase = 0x11A7
local LCount = 19
local VCount = 21
local TCount = 28
local NCount = VCount * TCount
local SCount = LCount * NCount

local function checked(value: any, where: string): string
    if type(value) ~= "string" then reject(where .. " must be a string") end
    return unicode.validate(value)
end

local function encodeCodepoints(points: any, first: number?, last: number?): string
    local begin = first or 1
    local final = last or #points
    local output = {}
    for index = begin, final do
        table.insert(output, builtinUtf8.char(points[index]))
    end
    return table.concat(output)
end

local function appendDecomposition(output: any, codepoint: number, useCompatibility: boolean)
    local syllableIndex = codepoint - SBase
    if syllableIndex >= 0 and syllableIndex < SCount then
        local leading = LBase + math.floor(syllableIndex / NCount)
        local vowel = VBase + math.floor((syllableIndex % NCount) / TCount)
        local trailingIndex = syllableIndex % TCount
        table.insert(output, leading)
        table.insert(output, vowel)
        if trailingIndex ~= 0 then table.insert(output, TBase + trailingIndex) end
        return
    end

    local mapping = if useCompatibility then compatibility[codepoint] else nil
    if mapping == nil then mapping = canonical[codepoint] end
    if mapping == nil then
        table.insert(output, codepoint)
        return
    end
    for _, value in ipairs(mapping) do
        appendDecomposition(output, value, useCompatibility)
    end
end

local function canonicalOrder(points: any)
    for index = 2, #points do
        local currentClass = combiningClasses[points[index]] or 0
        if currentClass ~= 0 then
            local position = index
            while position > 1 do
                local previousClass = combiningClasses[points[position - 1]] or 0
                if previousClass == 0 or previousClass <= currentClass then break end
                points[position], points[position - 1] =
                    points[position - 1], points[position]
                position -= 1
            end
        end
    end
end

local function hangulComposition(starter: number, combining: number): number?
    local leadingIndex = starter - LBase
    if leadingIndex >= 0 and leadingIndex < LCount then
        local vowelIndex = combining - VBase
        if vowelIndex >= 0 and vowelIndex < VCount then
            return SBase + (leadingIndex * VCount + vowelIndex) * TCount
        end
    end
    local syllableIndex = starter - SBase
    local trailingIndex = combining - TBase
    if syllableIndex >= 0 and syllableIndex < SCount
        and syllableIndex % TCount == 0
        and trailingIndex > 0 and trailingIndex < TCount
    then
        return starter + trailingIndex
    end
    return nil
end

local function canonicalComposition(points: any): any
    if #points == 0 then return points end
    local output = { points[1] }
    local starterPosition = 1
    local starter = points[1]
    local previousClass = 0
    for index = 2, #points do
        local codepoint = points[index]
        local currentClass = combiningClasses[codepoint] or 0
        local byCombining = compositions[starter]
        local composite = if byCombining == nil then nil else byCombining[codepoint]
        if composite == nil then composite = hangulComposition(starter, codepoint) end
        if composite ~= nil and (previousClass == 0 or previousClass < currentClass) then
            output[starterPosition] = composite
            starter = composite
        else
            table.insert(output, codepoint)
            if currentClass == 0 then
                starterPosition = #output
                starter = codepoint
            end
            previousClass = currentClass
        end
    end
    return output
end

function text.normalize(value: any, form: any?): string
    local source = checked(value, "normalize value")
    local selected = if form == nil then "NFC" else form
    if selected ~= "NFC" and selected ~= "NFD"
        and selected ~= "NFKC" and selected ~= "NFKD"
    then
        reject("normalization form must be NFC, NFD, NFKC, or NFKD")
    end
    local decomposed = {}
    local useCompatibility = selected == "NFKC" or selected == "NFKD"
    for _, codepoint in ipairs(unicode.codepoints(source)) do
        appendDecomposition(decomposed, codepoint, useCompatibility)
    end
    canonicalOrder(decomposed)
    if selected == "NFC" or selected == "NFKC" then
        decomposed = canonicalComposition(decomposed)
    end
    return encodeCodepoints(decomposed)
end

function text.case_fold(value: any): string
    local source = checked(value, "case_fold value")
    local output = {}
    for _, codepoint in ipairs(unicode.codepoints(source)) do
        local mapping = caseFolds[codepoint]
        if mapping == nil then
            table.insert(output, codepoint)
        else
            for _, folded in ipairs(mapping) do table.insert(output, folded) end
        end
    end
    return encodeCodepoints(output)
end

function text.trim(value: any): string
    local points = unicode.codepoints(checked(value, "trim value"))
    local first = 1
    while first <= #points and unicode.is_whitespace(points[first]) do first += 1 end
    local last = #points
    while last >= first and unicode.is_whitespace(points[last]) do last -= 1 end
    return encodeCodepoints(points, first, last)
end

function text.collapse_whitespace(value: any): string
    local points = unicode.codepoints(checked(value, "collapse_whitespace value"))
    local output = {}
    local pendingSpace = false
    for _, codepoint in ipairs(points) do
        if unicode.is_whitespace(codepoint) then
            pendingSpace = #output > 0
        else
            if pendingSpace then table.insert(output, 0x20) end
            pendingSpace = false
            table.insert(output, codepoint)
        end
    end
    return encodeCodepoints(output)
end

function text.split(value: any, separator: any, keep_empty: any?): any
    local source = checked(value, "split value")
    local delimiter = checked(separator, "split separator")
    if delimiter == "" then reject("split separator must not be empty") end
    local keepEmpty = if keep_empty == nil then true else keep_empty
    if type(keepEmpty) ~= "boolean" then
        reject("split keep_empty must be a boolean")
    end
    local output = {}
    local start = 1
    while true do
        local first, last = string.find(source, delimiter, start, true)
        local part = if first == nil then string.sub(source, start)
            else string.sub(source, start, first - 1)
        if keepEmpty or part ~= "" then table.insert(output, part) end
        if first == nil then break end
        start = last + 1
    end
    return table.freeze(output)
end

function text.tokens(value: any): any
    local points = unicode.codepoints(checked(value, "tokens value"))
    local output = {}
    local word = {}
    local function flushWord()
        if #word == 0 then return end
        table.insert(output, encodeCodepoints(word))
        word = {}
    end
    for _, codepoint in ipairs(points) do
        local category = unicode.classify(codepoint)
        if category == "letter" or category == "mark" or category == "number" then
            table.insert(word, codepoint)
        elseif unicode.is_whitespace(codepoint) or category == "separator" then
            flushWord()
        else
            flushWord()
            table.insert(output, builtinUtf8.char(codepoint))
        end
    end
    flushWord()
    return table.freeze(output)
end

local function prepared(value: any, options: any?): string
    local source = checked(value, "match value")
    if options == nil then return text.normalize(source, "NFC") end
    if type(options) ~= "table" then reject("match options must be a table") end
    for key in pairs(options) do
        if key ~= "normalization" and key ~= "case_fold"
            and key ~= "collapse_whitespace"
        then
            reject("match options contain unknown field " .. tostring(key))
        end
    end
    local normalizationValue = rawget(options, "normalization")
    local foldValue = rawget(options, "case_fold")
    local collapseValue = rawget(options, "collapse_whitespace")
    local normalization = if normalizationValue == nil then "NFC"
        else normalizationValue
    local fold = if foldValue == nil then false else foldValue
    local collapse = if collapseValue == nil then false else collapseValue
    if type(fold) ~= "boolean" or type(collapse) ~= "boolean" then
        reject("match boolean options must be booleans")
    end
    local output = text.normalize(source, normalization)
    if fold then
        output = text.case_fold(output)
        output = text.normalize(output, normalization)
    end
    if collapse then output = text.collapse_whitespace(output) end
    return output
end

function text.equals(left: any, right: any, options: any?): boolean
    return prepared(left, options) == prepared(right, options)
end

function text.contains(value: any, candidate: any, options: any?): boolean
    local source = prepared(value, options)
    local needle = prepared(candidate, options)
    return string.find(source, needle, 1, true) ~= nil
end

function text.starts_with(value: any, candidate: any, options: any?): boolean
    local source = prepared(value, options)
    local prefix = prepared(candidate, options)
    return string.sub(source, 1, #prefix) == prefix
end

function text.ends_with(value: any, candidate: any, options: any?): boolean
    local source = prepared(value, options)
    local suffix = prepared(candidate, options)
    return suffix == "" or string.sub(source, -#suffix) == suffix
end

return table.freeze(text)
'''
    return (
        template.replace("@@VERSION@@", PINNED_UNICODE_VERSION)
        .replace("@@CANONICAL@@", packed_mappings(canonical))
        .replace("@@COMPATIBILITY@@", packed_mappings(compatibility))
        .replace("@@COMBINING@@", packed_pairs(combining_classes()))
        .replace("@@COMPOSITION@@", packed_compositions(composition_maps()))
        .replace("@@CASEFOLD@@", packed_mappings(case_fold_maps()))
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="repository root",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed Luau module differs",
    )
    arguments = parser.parse_args()
    root = arguments.root.resolve()
    outputs = (
        (UTF8_OUTPUT, UTF8_OUTPUT_SHA256, render_utf8),
        (TEXT_OUTPUT, TEXT_OUTPUT_SHA256, render_text),
    )
    if arguments.check:
        for relative, pinned_digest, renderer in outputs:
            output = root / relative
            if not output.is_file():
                print(f"{relative}: is missing", flush=True)
                return 1
            committed = output.read_bytes()
            digest = hashlib.sha256(committed).hexdigest()
            if not pinned_digest or digest != pinned_digest:
                print(
                    f"{relative}: SHA-256 {digest} differs from pinned "
                    f"{pinned_digest or '<unset>'}",
                    flush=True,
                )
                return 1
            if unicodedata.unidata_version == PINNED_UNICODE_VERSION:
                generated = renderer().encode("utf-8")
                if committed != generated:
                    print(
                        f"{relative}: differs from pinned Unicode generation",
                        flush=True,
                    )
                    return 1
        print(
            f"Unicode Luau check OK ({len(outputs)} modules, UCD "
            f"{PINNED_UNICODE_VERSION})."
        )
        return 0
    for relative, _pinned_digest, renderer in outputs:
        generated = renderer()
        output = root / relative
        output.write_text(generated, encoding="utf-8", newline="\n")
        digest = hashlib.sha256(generated.encode("utf-8")).hexdigest()
        print(
            f"Unicode Luau generated ({len(generated)} bytes, SHA-256 "
            f"{digest}): {relative}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
