#!/usr/bin/env python3
"""Generate pinned Unicode data modules from Python's UCD.

Python owns only offline data derivation. Hand-maintained Luau modules own every
runtime algorithm; Framework execution never imports Python or host Unicode
tables. Regeneration deliberately refuses a different UCD version so an SDK
Unicode upgrade must be an explicit identity-moving change.

The derived category data is distributed with the Unicode License v3 notice in
``modules/task/runtime/UNICODE-LICENSE.txt``.
"""

from __future__ import annotations

import argparse
import hashlib
import unicodedata
from pathlib import Path


PINNED_UNICODE_VERSION = "15.0.0"
UTF8_DATA_OUTPUT = Path("modules/task/runtime/unicode-utf8-data.luau")
UTF8_DATA_OUTPUT_SHA256 = "c68e79be9cfa2c6ef9679c41ff30fedee7e4230dcafe1d918496d9b1b4796033"
TEXT_DATA_OUTPUT = Path("modules/task/runtime/unicode-text-data.luau")
TEXT_DATA_OUTPUT_SHA256 = "e7a2fbc53ec58081b78fa0c4ce56ac20f10a745d9ba3124f10d38e117282cfa4"

MAJOR_CATEGORY_NAMES = {
    "C": "other",
    "L": "letter",
    "M": "mark",
    "N": "number",
    "P": "punctuation",
    "S": "symbol",
    "Z": "separator",
}

# Unicode White_Space from PropList for Unicode 15.0.0. These authored ranges
# make the property explicit; Python's str.isspace also includes four legacy C0
# information separators and therefore is not the property this API promises.
WHITE_SPACE_RANGES = (
    (0x0009, 0x000D),
    (0x0020, 0x0020),
    (0x0085, 0x0085),
    (0x00A0, 0x00A0),
    (0x1680, 0x1680),
    (0x2000, 0x200A),
    (0x2028, 0x2029),
    (0x202F, 0x202F),
    (0x205F, 0x205F),
    (0x3000, 0x3000),
)


def major_category_ranges() -> list[tuple[int, int, str]]:
    ranges: list[tuple[int, int, str]] = []
    start = 0
    previous = unicodedata.category(chr(0))[0]
    for codepoint in range(1, 0x110000):
        current = unicodedata.category(chr(codepoint))[0]
        if current == previous:
            continue
        ranges.append((start, codepoint - 1, MAJOR_CATEGORY_NAMES[previous]))
        start = codepoint
        previous = current
    ranges.append((start, 0x10FFFF, MAJOR_CATEGORY_NAMES[previous]))
    return ranges


def lua_ranges(rows: list[tuple[int, int, str]]) -> str:
    return "\n".join(
        f'    {{{start}, {end}, "{name}"}},' for start, end, name in rows
    )


def lua_numeric_ranges(rows: tuple[tuple[int, int], ...]) -> str:
    return "\n".join(f"    {{{start}, {end}}}," for start, end in rows)


def render_utf8_data() -> str:
    if unicodedata.unidata_version != PINNED_UNICODE_VERSION:
        raise SystemExit(
            "generate_unicode_luau.py requires Python UCD "
            f"{PINNED_UNICODE_VERSION}, got {unicodedata.unidata_version}"
        )

    return f'''-- GENERATED by scripts/generate_unicode_luau.py; do not edit.
-- Derived Unicode 15.0 category and White_Space data only.
-- Runtime algorithms live in the hand-maintained utf8.luau module.
--!strict

local data = {{
    unicode_version = "{PINNED_UNICODE_VERSION}",
    category_ranges = {{
{lua_ranges(major_category_ranges())}
    }},
    white_space_ranges = {{
{lua_numeric_ranges(WHITE_SPACE_RANGES)}
    }},
}}

return table.freeze(data)
'''


def decomposition_maps() -> tuple[
    list[tuple[int, list[int]]], list[tuple[int, list[int]]]
]:
    canonical: list[tuple[int, list[int]]] = []
    compatibility: list[tuple[int, list[int]]] = []
    for codepoint in range(0x110000):
        decomposition = unicodedata.decomposition(chr(codepoint))
        if not decomposition:
            continue
        fields = decomposition.split()
        tagged = fields[0].startswith("<")
        mapping_start = 1 if tagged else 0
        values = [int(field, 16) for field in fields[mapping_start:]]
        (compatibility if tagged else canonical).append((codepoint, values))
    return canonical, compatibility


def combining_classes() -> list[tuple[int, int]]:
    return [
        (codepoint, value)
        for codepoint in range(0x110000)
        if (value := unicodedata.combining(chr(codepoint))) != 0
    ]


def case_fold_maps() -> list[tuple[int, list[int]]]:
    rows: list[tuple[int, list[int]]] = []
    for codepoint in range(0x110000):
        source = chr(codepoint)
        folded = source.casefold()
        if folded != source:
            rows.append((codepoint, [ord(value) for value in folded]))
    return rows


def composition_maps() -> list[tuple[int, int, int]]:
    rows: list[tuple[int, int, int]] = []
    for codepoint in range(0x110000):
        decomposition = unicodedata.decomposition(chr(codepoint))
        if not decomposition or decomposition.startswith("<"):
            continue
        values = [int(field, 16) for field in decomposition.split()]
        if len(values) != 2 or unicodedata.combining(chr(values[0])) != 0:
            continue
        source = "".join(chr(value) for value in values)
        if unicodedata.normalize("NFC", source) == chr(codepoint):
            rows.append((values[0], values[1], codepoint))
    return rows


def packed_mappings(rows: list[tuple[int, list[int]]]) -> str:
    return "\n".join(
        f"{codepoint}:" + ",".join(str(value) for value in values)
        for codepoint, values in rows
    )


def packed_pairs(rows: list[tuple[int, int]]) -> str:
    return "\n".join(f"{left}:{right}" for left, right in rows)


def packed_compositions(rows: list[tuple[int, int, int]]) -> str:
    return "\n".join(
        f"{starter},{combining}:{composite}"
        for starter, combining, composite in rows
    )


def render_text_data() -> str:
    if unicodedata.unidata_version != PINNED_UNICODE_VERSION:
        raise SystemExit(
            "generate_unicode_luau.py requires Python UCD "
            f"{PINNED_UNICODE_VERSION}, got {unicodedata.unidata_version}"
        )

    canonical, compatibility = decomposition_maps()
    template = r'''-- GENERATED by scripts/generate_unicode_luau.py; do not edit.
-- Derived Unicode 15.0 normalization and full case-folding data only.
-- Runtime algorithms live in the hand-maintained text.luau module.
--!strict

local data = {
    unicode_version = "@@VERSION@@",
    canonical = [=[@@CANONICAL@@]=],
    compatibility = [=[@@COMPATIBILITY@@]=],
    combining_classes = [=[@@COMBINING@@]=],
    compositions = [=[@@COMPOSITION@@]=],
    case_folds = [=[@@CASEFOLD@@]=],
}

return table.freeze(data)
'''
    return (
        template.replace("@@VERSION@@", PINNED_UNICODE_VERSION)
        .replace("@@CANONICAL@@", packed_mappings(canonical))
        .replace("@@COMPATIBILITY@@", packed_mappings(compatibility))
        .replace("@@COMBINING@@", packed_pairs(combining_classes()))
        .replace("@@COMPOSITION@@", packed_compositions(composition_maps()))
        .replace("@@CASEFOLD@@", packed_mappings(case_fold_maps()))
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="repository root",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when a committed Unicode data module differs",
    )
    arguments = parser.parse_args()
    root = arguments.root.resolve()
    outputs = (
        (UTF8_DATA_OUTPUT, UTF8_DATA_OUTPUT_SHA256, render_utf8_data),
        (TEXT_DATA_OUTPUT, TEXT_DATA_OUTPUT_SHA256, render_text_data),
    )
    if arguments.check:
        for relative, pinned_digest, renderer in outputs:
            output = root / relative
            if not output.is_file():
                print(f"{relative}: is missing", flush=True)
                return 1
            committed = output.read_bytes()
            digest = hashlib.sha256(committed).hexdigest()
            if not pinned_digest or digest != pinned_digest:
                print(
                    f"{relative}: SHA-256 {digest} differs from pinned "
                    f"{pinned_digest or '<unset>'}",
                    flush=True,
                )
                return 1
            if unicodedata.unidata_version == PINNED_UNICODE_VERSION:
                generated = renderer().encode("utf-8")
                if committed != generated:
                    print(
                        f"{relative}: differs from pinned Unicode generation",
                        flush=True,
                    )
                    return 1
        print(
            f"Unicode Luau check OK ({len(outputs)} modules, UCD "
            f"{PINNED_UNICODE_VERSION})."
        )
        return 0
    for relative, _pinned_digest, renderer in outputs:
        generated = renderer()
        output = root / relative
        output.write_text(generated, encoding="utf-8", newline="\n")
        digest = hashlib.sha256(generated.encode("utf-8")).hexdigest()
        print(
            f"Unicode Luau generated ({len(generated)} bytes, SHA-256 "
            f"{digest}): {relative}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
