# Manifest-driven module autoloader.

include(cmake/tools.cmake)

function(cpp_define_module MODULE_ROOT_DIR DIR_NAME)
    set(MODULE_PATH "${MODULE_ROOT_DIR}/${DIR_NAME}")
    set(MANIFEST_FILE "${MODULE_PATH}/manifest.txt")

    if(NOT EXISTS "${MANIFEST_FILE}")
        return()
    endif()

    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${MANIFEST_FILE}")

    cpp_parse_manifest("${MANIFEST_FILE}" MANIFEST)

    set(MODULE_SHORT_NAME "${MANIFEST_MODULE_NAME}")
    if(MODULE_SHORT_NAME STREQUAL "")
        set(MODULE_SHORT_NAME "${DIR_NAME}")
    endif()

    set(MODULE_NAME "${PROJECT_NAME}_${MODULE_SHORT_NAME}")
    set(MODULE_VERSION "${MANIFEST_VERSION}")
    set(MODULE_DISPLAY_NAME "${MODULE_SHORT_NAME}")
    if(MODULE_DISPLAY_NAME STREQUAL "")
        set(MODULE_DISPLAY_NAME "${MODULE_NAME}")
    endif()

    cpp_manifest_supports_current_platform(
        "${MANIFEST_MODULE_PLATFORMS}"
        MODULE_PLATFORM_SUPPORTED
    )
    if(NOT MODULE_PLATFORM_SUPPORTED)
        cpp_get_platform_key(CURRENT_PLATFORM)
        message(STATUS "[AutoLoader] Skipping: ${MODULE_DISPLAY_NAME} (unsupported on ${CURRENT_PLATFORM})")
        return()
    endif()

    cpp_manifest_normalize_module_type("${MANIFEST_MODULE_TYPE}" MODULE_KIND)

    message(STATUS "[AutoLoader] Configuring: ${MODULE_DISPLAY_NAME} (v${MODULE_VERSION})")

    # A module owns its vendored third-party under external/.
    # When that directory carries a CMakeLists.txt, build it here (Pass 1: Define)
    # so its targets exist before this module is linked (Pass 2). This keeps a
    # single-module library confined to the module — nothing leaks to the
    # top-level build; the module still declares the concrete targets it links
    # in its manifest [dependencies].
    if(EXISTS "${MODULE_PATH}/external/CMakeLists.txt")
        add_subdirectory(
            "${MODULE_PATH}/external"
            "${CMAKE_BINARY_DIR}/modules/${DIR_NAME}/external"
            EXCLUDE_FROM_ALL
        )
    endif()

    file(GLOB_RECURSE SRC_FILES CONFIGURE_DEPENDS
        "${MODULE_PATH}/source/*.cpp"
    )
    file(GLOB_RECURSE HDR_FILES CONFIGURE_DEPENDS
        "${MODULE_PATH}/source/*.hpp"
    )

    if(NOT SRC_FILES)
        set(DUMMY_FILE "${CMAKE_BINARY_DIR}/modules/${DIR_NAME}/AutoDummy.cpp")
        file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/modules/${DIR_NAME}")

        if(NOT EXISTS "${DUMMY_FILE}")
            file(WRITE "${DUMMY_FILE}" "// Auto-generated by the module build system.\n")
        endif()

        list(APPEND SRC_FILES "${DUMMY_FILE}")

        message(STATUS "  -> [Info] No source files found. Generated dummy file to allow library creation.")
    endif()

    add_library(${MODULE_NAME} ${MODULE_KIND} ${SRC_FILES} ${HDR_FILES})
    cpp_apply_safety_profile(${MODULE_NAME})

    set_target_properties(${MODULE_NAME} PROPERTIES
        VERSION ${MODULE_VERSION}
        CPP_DEPS_PUBLIC "${MANIFEST_DEPS_PUBLIC}"
        CPP_DEPS_PRIVATE "${MANIFEST_DEPS_PRIVATE}"
        CPP_DEPS_PUBLIC_WINDOWS "${MANIFEST_DEPS_PUBLIC_WINDOWS}"
        CPP_DEPS_PRIVATE_WINDOWS "${MANIFEST_DEPS_PRIVATE_WINDOWS}"
        CPP_DEPS_PUBLIC_LINUX "${MANIFEST_DEPS_PUBLIC_LINUX}"
        CPP_DEPS_PRIVATE_LINUX "${MANIFEST_DEPS_PRIVATE_LINUX}"
        CPP_DEPS_PUBLIC_MACOS "${MANIFEST_DEPS_PUBLIC_MACOS}"
        CPP_DEPS_PRIVATE_MACOS "${MANIFEST_DEPS_PRIVATE_MACOS}"
    )

    string(TOUPPER ${MODULE_NAME} UPPER_NAME)
    target_compile_definitions(${MODULE_NAME} PRIVATE ${UPPER_NAME}_BUILD)

    target_compile_features(${MODULE_NAME} PUBLIC cxx_std_23)

    cpp_apply_platform_definitions(
        ${MODULE_NAME}
        "${MANIFEST_DEFINES_PUBLIC}"
        "${MANIFEST_DEFINES_PRIVATE}"
        "${MANIFEST_DEFINES_PUBLIC_WINDOWS}"
        "${MANIFEST_DEFINES_PRIVATE_WINDOWS}"
        "${MANIFEST_DEFINES_PUBLIC_LINUX}"
        "${MANIFEST_DEFINES_PRIVATE_LINUX}"
        "${MANIFEST_DEFINES_PUBLIC_MACOS}"
        "${MANIFEST_DEFINES_PRIVATE_MACOS}"
    )

    target_include_directories(${MODULE_NAME}
        PUBLIC
            $<BUILD_INTERFACE:${MODULE_PATH}/source>
            $<BUILD_INTERFACE:${MODULE_PATH}/source/${DIR_NAME}>
            $<INSTALL_INTERFACE:include>
    )

    if(MANIFEST_BUILD_PCH)
        set(PCH_HEADER "${MANIFEST_BUILD_PCH}")
        if(NOT IS_ABSOLUTE "${PCH_HEADER}")
            set(PCH_HEADER "${MODULE_PATH}/${PCH_HEADER}")
        endif()

        if(EXISTS "${PCH_HEADER}")
            target_precompile_headers(${MODULE_NAME} PRIVATE "${PCH_HEADER}")
        else()
            message(WARNING "[${MODULE_NAME}] PCH header not found: ${PCH_HEADER}")
        endif()
    endif()

    if(MANIFEST_BUILD_UNITY)
        set_target_properties(${MODULE_NAME} PROPERTIES UNITY_BUILD ON)
    endif()

endfunction()

function(cpp_link_module MODULE_ROOT_DIR DIR_NAME)
    set(MODULE_PATH "${MODULE_ROOT_DIR}/${DIR_NAME}")
    set(MANIFEST_FILE "${MODULE_PATH}/manifest.txt")

    # Resolve module name from manifest (same logic as cpp_define_module)
    set(MODULE_SHORT_NAME "${DIR_NAME}")
    if(EXISTS "${MANIFEST_FILE}")
        cpp_parse_manifest("${MANIFEST_FILE}" MANIFEST)
        if(NOT MANIFEST_MODULE_NAME STREQUAL "")
            set(MODULE_SHORT_NAME "${MANIFEST_MODULE_NAME}")
        endif()
    endif()

    set(MODULE_NAME "${PROJECT_NAME}_${MODULE_SHORT_NAME}")

    if(NOT TARGET ${MODULE_NAME})
        return()
    endif()

    get_target_property(DEPS_PUBLIC ${MODULE_NAME} CPP_DEPS_PUBLIC)
    get_target_property(DEPS_PRIVATE ${MODULE_NAME} CPP_DEPS_PRIVATE)
    get_target_property(DEPS_PUBLIC_WINDOWS ${MODULE_NAME} CPP_DEPS_PUBLIC_WINDOWS)
    get_target_property(DEPS_PRIVATE_WINDOWS ${MODULE_NAME} CPP_DEPS_PRIVATE_WINDOWS)
    get_target_property(DEPS_PUBLIC_LINUX ${MODULE_NAME} CPP_DEPS_PUBLIC_LINUX)
    get_target_property(DEPS_PRIVATE_LINUX ${MODULE_NAME} CPP_DEPS_PRIVATE_LINUX)
    get_target_property(DEPS_PUBLIC_MACOS ${MODULE_NAME} CPP_DEPS_PUBLIC_MACOS)
    get_target_property(DEPS_PRIVATE_MACOS ${MODULE_NAME} CPP_DEPS_PRIVATE_MACOS)

    cpp_link_platform_dependencies(
        ${MODULE_NAME}
        "${DEPS_PUBLIC}"
        "${DEPS_PRIVATE}"
        "${DEPS_PUBLIC_WINDOWS}"
        "${DEPS_PRIVATE_WINDOWS}"
        "${DEPS_PUBLIC_LINUX}"
        "${DEPS_PRIVATE_LINUX}"
        "${DEPS_PUBLIC_MACOS}"
        "${DEPS_PRIVATE_MACOS}"
    )

endfunction()


function(cpp_scan_and_load_modules)
    foreach(ROOT_PATH IN LISTS ARGN)
        if(ROOT_PATH STREQUAL "")
            continue()
        endif()

        if(NOT IS_DIRECTORY "${ROOT_PATH}")
            message(WARNING "[AutoLoader] Module root not found: ${ROOT_PATH}")
            continue()
        endif()

        file(GLOB CHILDREN RELATIVE "${ROOT_PATH}" "${ROOT_PATH}/*")

        set(MODULE_DIRS "")
        foreach(CHILD ${CHILDREN})
            if(IS_DIRECTORY "${ROOT_PATH}/${CHILD}" AND EXISTS "${ROOT_PATH}/${CHILD}/manifest.txt")
                list(APPEND MODULE_DIRS "${CHILD}")
            elseif(IS_DIRECTORY "${ROOT_PATH}/${CHILD}")
                if(CPP_VERBOSE_AUTOLOADER)
                    message(STATUS "[AutoLoader] Skipping '${ROOT_PATH}/${CHILD}' (no manifest.txt)")
                endif()
            endif()
        endforeach()

        # Pass 1: Define
        foreach(CHILD ${MODULE_DIRS})
            cpp_define_module("${ROOT_PATH}" "${CHILD}")
        endforeach()

        # Pass 2: Link
        foreach(CHILD ${MODULE_DIRS})
            cpp_link_module("${ROOT_PATH}" "${CHILD}")
        endforeach()
    endforeach()
endfunction()
